import { Metadata } from "next";
import Link from "next/link";
import Logo from "@/components/common/Logo";
import Input from "@/components/inputElements/Input";

export const metadata: Metadata = {
	title: "Register | Entertainment Web App",
	description: "Generated by create next app",
};

const Login = () => {
	return (
		<main className='center_content'>
			<Logo />
			<div className='mt-20 bg-brandSemiDarkBlue w-fit p-8 rounded-3xl min-w-[400px]'>
				<h1 className='mb-10 heading_l'>Sign Up</h1>
				<div className='flex flex-col gap-6'>
					<Input />
					<Input />
					<Input />
					<button className='button mt-4'>Create an account</button>
					<span className='body_m text-center'>
						Already have an account?{" "}
						<Link href='/login' className='text-brandRed'>
							Login
						</Link>
					</span>
				</div>
			</div>
		</main>
	);
};
export default Login;
